import DS from 'ember-data';
export default DS.Model.extend({
    "POOL": DS.attr('number'),
    "URL": DS.attr('string'),
    "Status": DS.attr('string'),
    "Priority": DS.attr('number'),
    "Quota": DS.attr('number'),
    "Long Poll": DS.attr('string'),
    "Getworks": DS.attr('number'),
    "Accepted": DS.attr('number'),
    "Rejected": DS.attr('number'),
    "Works": DS.attr('number'),
    "Discarded": DS.attr('number'),
    "Stale": DS.attr('number'),
    "Get Failures": DS.attr('number'),
    "Remote Failures": DS.attr('number'),
    "User": DS.attr('string'),
    "Last Share Time": DS.attr('number'),
    "Diff1 Shares": DS.attr('number'),
    "Proxy Type": DS.attr('string'),
    "Proxy": DS.attr('string'),
    "Difficulty Accepted": DS.attr('number'),
    "Difficulty Rejected": DS.attr('number'),
    "Difficulty Stale": DS.attr('number'),
    "Last Share Difficulty": DS.attr('number'),
    "Has Stratum": DS.attr('boolean'),
    "Stratum Active": DS.attr('boolean'),
    "Stratum URL": DS.attr('string'),
    "Has GBT": DS.attr('boolean'),
    "Best Share": DS.attr('number'),
    "Pool Rejected%": DS.attr('number'),
    "Pool Stale%": DS.attr('number')
});
